#[build]
#target = "riscv64gc-unknown-linux-gnu"

# Assuming that linker and ar are coming from native
# Ubuntu packages.
[target.riscv64gc-unknown-linux-gnu]
linker    = "riscv64-linux-gnu-g++"
ar        = "riscv64-linux-gnu-ar"
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
#rustflags = ["-C", "target-feature=+crt-static"]
